### PR TITLE
Fix: improve trim rows plugin performance on ie

### PR DESCRIPTION
**Pull request by ghost**
## Context

Filter plugin of handsontable-pro depend on trimRows, the function createMap of trimRows use a loop to figure out which row should not be trimmed, original time complex is O(n * m), we try use Set interface to decrease to O(n * log m).  An example is posted in [official version](http://jsfiddle.net/weili_tw/v5k7934d/) and [fixed version](http://jsfiddle.net/weili_tw/1s6gm24x/), the first one use the lib from official site, and the second use that we fixed. On my machine, the first one spend about 10s to filter first row, the second one need about 5s.

## How has this been tested?

Yes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Related issue(s):
none
## Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by AMBudnik** [comment]
Hi @WeiLi-TW 

Thank you for sharing the PR and signing the CLA. Can you also add some tests?

**Comment by WeiLi-TW** [comment]
Hi @AMBudnik 
I don't understand about add some tests meaning, should i add test for performance improving or logic correctness.

**Comment by AMBudnik** [comment]
Sorry for the misunderstanding. To pull a code we need to have a test scenario for the new change. Here is a sample test for the `obsereChanges` plugin fix https://github.com/handsontable/handsontable/pull/4638/files

**Comment by WeiLi-TW** [comment]
We change trimRow way but not change the behavior, so the logic correctness should already keep by original unit test and e2e test. like this one https://github.com/handsontable/handsontable-pro/pull/20/files#diff-318247fc72eefbc583fc94287fde3c79R25 and this one https://github.com/handsontable/handsontable-pro/pull/20/files#diff-318247fc72eefbc583fc94287fde3c79R45.

**Comment by wojciechczerniak** [comment]
We're archiving this repo. We're going to move forward on this issue in https://github.com/handsontable/handsontable. Thank you for your contribution.

**Pull request closed without merging**
