### PR TITLE
language for zh-TW and zh-CN

### PR DESCRIPTION
**Pull request by yuda-lyu**
​Hi Handsontable,

Because I always have the need to provide Chinese language for users in my web, so I have to add the Simplified and Traditional language for table in every update.

The attachments are the language file (Javascript) that I am currently modifying for version 1.16,
maybe the files can help Handsontable to support for Chinese language in the future.

[zh-CN.js.txt](https://github.com/handsontable/handsontable-pro/files/1763144/zh-CN.js.txt)
[zh-TW.js.txt](https://github.com/handsontable/handsontable-pro/files/1763145/zh-TW.js.txt)

### CODE REVIEW

**Comment by AMBudnik** [comment]
Please sign the [CLA](https://docs.google.com/forms/d/1sNbsA7MGelGNxsBRvBoY3swq7YEMYhXNpR7NPk4tWPo/edit#response=ACYDBNhV1MTfdr_NRjtxSKISOkC3HVhagIFXk_ZELGMEB_3L4uIlD2CG9AtqXYs). We are not able to do anything with the code or translation without it.

**Comment by yuda-lyu** [comment]
ok! Sorry I do not understand how to submit the CLA, it's my first time.
Now I submit a google form by CLA hyperlinks in before email, maybe It's
done.

2018-03-01 22:14 GMT+08:00 Aleksandra Budnik <notifications@github.com>:

**Comment by AMBudnik** [comment]
Yes, it is completed. Thank you.
Now, the Travis test does not pass as the files aren't loaded properly (you would need to create a fork of the repository (CE, not PRO) then add the language files and then push a PR). If you are interested in creating a pull request that we can merge please check this quick tutorial on how to do it https://docs.handsontable.com/pro/1.16.0/tutorial-internationalization.html
or if you want us to do the rest it's also OK. I will then create the PR on CE board and just ask you for translation confirmation.

**Comment by AMBudnik** [comment]
I am closing this PR. As agreed with the Author we will stay with this translation https://github.com/handsontable/handsontable/pull/4919

**Pull request closed without merging**
